#!/bin/bash

set -eux

OPENSTACK_REPOS="glance horizon keystone nova python-keystoneclient \
                 python-novaclient swift"
OPENSTACK_DEV_REPOS="devstack"
CITRIX_REPOS="glance-build infrastructure keystone-build manifests nova-build \
              openstackx os-vpx python-keystoneclient-build \
              python-novaclient-build qa swift-build"
HTTP_URL="http://github.com"
HTTPS_URL="https://github.com"
GIT_URL="git://github.com"
REPO_CACHE="/openstack_build_cache/repos"

if ${GIT_PROTOCOL-false}
then
  url="$GIT_URL"
else
  url="$HTTPS_URL"
fi

wipe()
{
  sudo rm -rf "$REPO_CACHE"
}
#trap wipe ERR

update()
{
  local repo="$1"
  local owners="$2"

  cd "$REPO_CACHE"
  if [ ! -d $repo ]
  then
    sudo mkdir $repo
    sudo chown jenkins $repo
    cd $repo
    git init --bare
    local first=true
    for owner in $owners
    do
      git remote add "$owner" --mirror "$url/$owner/$repo"
    done
  else
    cd $repo
  fi
  git remote update
  git update-server-info
}

sudo mkdir -p "$REPO_CACHE"
for repo in $OPENSTACK_REPOS
do
  update "$repo" "openstack citrix-openstack"
done
for repo in $OPENSTACK_DEV_REPOS
do
  update "$repo" "openstack-dev"
done
for repo in $CITRIX_REPOS
do
  update "$repo" "citrix-openstack"
done
